### ISSUE TITLE
Auto-check

### ISSUE THREAD

**Issue by orschiro** [languagetool-org/languagetool-browser-addon#47] opened 2016-05-06 09:09 UTC
Dear all, 

Thank you so much for your work to provide this Chrome extension!

I was wondering whether it was possible to add an auto-check feature. 

This is, for example, provided by [Grammarly](https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen) or [Ginger Spellcheck](https://chrome.google.com/webstore/detail/spell-checker-and-grammar/kdfieneakcjfaiglcfcgkidlkmlijjnh) that both automatically check the text while composing. 

This is a very intuitive and user-friendly feature. 

What do you think?

Thankfully,

~Robert

**Comment by danielnaber** [comment] 2016-05-06 09:29
It would be great, and help is welcome. It seems to be difficult, though. Also see #41, I'm closing this issue as it's basically a duplicate of that issue.

**Closed by danielnaber** 2016-05-06 09:29 UTC

**Comment by orschiro** [comment] 2016-05-06 12:40
Thank you very much @danielnaber!

I will follow-up on the other issue. 

Hopefully someone can indeed assist with this one. 

~Robert
