### ISSUE TITLE
not working with recent Firefox Nightly

### ISSUE THREAD

**Issue by newsjunkie247** [languagetool-org/languagetool-browser-addon#97] opened 2016-11-22 19:46 UTC
Is anyone else having trouble with the addon in latest Firefox nightlies/plus the most recent update? Currently it just stays blank when I try to open it.

**Comment by danielnaber** [comment] 2016-11-22 20:01
I can reproduce this, an error is printed to the console: `Extension error: TypeError: items is undefined moz-extension://5aef3d49-e012-451b-8fbb-74cdaac3ca7f/popup.js 490`. This is probably an issue in Nightly I guess and will hopefully be fixed soon.

**Comment by danielnaber** [comment] 2017-01-04 21:44
Still reproducible with today's nightly (2017-01-04).

**Comment by jjnilton** [comment] 2017-01-06 20:44
I get the same problem with Firefox Developer Edition (52.0a2).

**Comment by honggoff** [comment] 2017-01-13 22:40
I looked into this issue and found out that Mozilla changed the interface of the storage object in the development branch. The get() method no longer takes a callback argument but returns a promise instead.

See this commit, that introduced it: https://hg.mozilla.org/mozilla-central/rev/cf7a2d48ca5d#l2.12
The reason is discussed in this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1258139
The documentation has also been updated: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/Storage/StorageArea/get

This seems like a breaking API change to me, I don't know how or when this would be merged into Firefox stable. Also, the interface is now different from Chrome, which seems very unfortunate.

**Comment by honggoff** [comment] 2017-01-14 23:01
I'm afraid the change I mentioned in my last comment was a red herring, the API still seems to work as it did before. Instead, the following warning in the console caught my eye:

    Unchecked lastError value: Error: Please set webextensions.storage.sync.enabled to true in about:config

Setting the mentioned configuration entry indeed fixes the problem for me without any code change.

**Comment by danielnaber** [comment] 2017-01-28 13:38
As this now also affects FF beta, I added a workaround. It needs to go through the Mozilla review first, this might take a few days.

**Closed by danielnaber** 2017-01-28 13:38 UTC
Labels: Firefox
