### ISSUE TITLE
Addon is reason slow down of firefox at the twitter.com

### ISSUE THREAD

**Issue by dimahetman** [languagetool-org/languagetool-browser-addon#207] opened 2018-02-01 21:00 UTC
after several seconds since  twitter.com was opened firefox was freezen two times by several seconds with opened warning panel about it.
firefox 58.0.1 (64 bit) for
Ubuntu 16.04.3 LTS

**Comment by danielnaber** [comment] 2018-02-01 21:05
Thanks for the report, can you reproduce this behavior? I'm using the same browser and OS and it works for me. Are you using the current version of the add-on?

**Comment by dimahetman** [comment] 2018-02-01 21:10
I can send a light screencast.

**Comment by dimahetman** [comment] 2018-02-01 21:12
add after my nickname "@" gmail domain = is my e-mail

**Comment by dimahetman** [comment] 2018-02-01 21:14
LanguageTool version is 1.0.34

**Comment by danielnaber** [comment] 2018-02-01 21:16
> I can send a light screencast.

Please do.

**Comment by dimahetman** [comment] 2018-02-01 21:21
[Uploading Скрынкаст, 02.02.2018 00:03:43.webm.zip…]()
in the screencast, I did not have time to open Twitter for the second time, but the browser reported a slowdown on a blank page after addon was switch on

**Comment by dimahetman** [comment] 2018-02-01 21:29
there is a possibility that this is due to the combination of my addons

**Comment by danielnaber** [comment] 2018-02-01 21:31
Your attachment didn't quite make it to github it seems, the link is broken.

> there is a possibility that this is due to the combination of my addons

Maybe, could you check it by turning off (you don't need to deinstall) other add-ons?

**Comment by dimahetman** [comment] 2018-02-01 21:35
experimentally found that together, work, badly only, languegetool and mate translate, other addons never mind. thank you

**Comment by danielnaber** [comment] 2018-02-02 07:54
So I understand this issue only happens when you have "Make translate" installed at the same time?

**Comment by danielnaber** [comment] 2018-08-02 22:49
Closing, as there was no further feedback.

**Closed by danielnaber** 2018-08-02 22:49 UTC
